### ISSUE TITLE
Creates peer dependency issue with firebase-admin - Unable to do firebase deploy

### ISSUE THREAD

**Issue by fnisarm** [benweier/connect-session-firebase#137]
This is happening after upgrading firebase-admin to version 11.0
Tried downgrading firebase-admin to version 10 as well still the same issue

> 
i  functions: preparing functions directory for uploading...
i  functions: packaged C:\src\pwa\neelithal\functions (152.79 KB) for uploading
+  functions: functions folder uploaded successfully
i  hosting[neelithal-webapp]: beginning deploy...
i  hosting[neelithal-webapp]: found 51 files in public
+  hosting[neelithal-webapp]: file upload complete
i  functions: updating Node.js 16 function neelithalWebapp(us-central1)...
Build failed: npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: connect-session-firebase@5.13.0
npm ERR! Found: firebase-admin@10.3.0
npm ERR! node_modules/firebase-admin
npm ERR!   firebase-admin@"^10.3.0" from the root project
npm ERR!   peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0" from firebase-functions@3.20.0
npm ERR!   node_modules/firebase-functions
npm ERR!     firebase-functions@"^3.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-admin@"~5.13.0" from connect-session-firebase@5.13.0
npm ERR! node_modules/connect-session-firebase
npm ERR!   connect-session-firebase@"^5.13.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: firebase-admin@5.13.1
npm ERR! node_modules/firebase-admin
npm ERR!   peer firebase-admin@"~5.13.0" from connect-session-firebase@5.13.0
npm ERR!   node_modules/connect-session-firebase
npm ERR!     connect-session-firebase@"^5.13.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /www-data-home/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2022-10-11T15_47_18_592Z-debug-0.log; Error ID: beaf8772

Functions deploy had errors with the following functions:
        neelithalWebapp(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
PS C:\src\pwa\neelithal\functions>

**Comment by fnisarm** [comment]
@benweier can you please update on this ?

**Comment by benweier** [comment]
Sorry @fnisarm I didn't see this until the mention. I will look into the issue this week and aim to get a new version published as soon as I can

**Comment by benweier** [comment]
Thank you for your patience @fnisarm. `11.0.0` has just been published to npm and expects any `firebase-admin@11.x.x` peer
