### ISSUE TITLE
Unhandled Promise rejection warning when no sessions present

### ISSUE THREAD

**Issue by henkiejan** [benweier/connect-session-firebase#33]
When no sessions present, FirebaseStore.prototype.reap gives an unhandled Promise rejection warning in line 168:

```
167         if (!snapshot.exists()) {
168               return fn();
169         }
```
TypeError: fn is not a function

fn() should be fn, or something else?

**Comment by benweier** [comment]
Thanks @henkiejan this should be resolved in `4.1.0` now
