### ISSUE TITLE
Sessions aren't lasting more than 6 hours

### ISSUE THREAD

**Issue by johnkorzhuk** [benweier/connect-session-firebase#63]
In your documentation, it says to use reapInterval to assign a duration to session cleanup. The default is 6 hours. I assume this means that every 6 hours the user's session expires and your middleware removes it from the database. I want my users to stay signed in for 3 days so I set reapInterval to 259200000. However, my sessions are still expiring after 6 hours.

I'm I mistaken for thinking this is how you increase session duration? 

Perhaps I'm supposed to be setting a config in express-session?

Here's the relevant code in my codebase:

```javascript
import morgan from 'morgan';
import bodyParser from 'body-parser';
import compression from 'compression';
import helmet from 'helmet';
import admin from 'firebase-admin';
import session from 'express-session';
import sessionFirebase from 'connect-session-firebase';

const firebaseConfig = MY_FIREBASE_CONFIG

const isDev = process.env.NODE_ENV === 'development';
const isProd = process.env.NODE_ENV === 'production';

const firebase = admin.initializeApp(
  {
    credential: admin.credential.cert(firebaseConfig),
    databaseURL: 'https://collaborate-200e0.firebaseio.com'
  },
  'server'
);

const FirebaseStore = sessionFirebase(session);

export default server => {
  if (isProd) {
    server.use(compression());
    server.use(helmet());
  }

  server.use(bodyParser.json());
  server.use(bodyParser.urlencoded({ extended: true }));
  server.use((req, res, next) => {
    req.firebaseServer = firebase;
    next();
  });
  server.use(
    session({
      store: new FirebaseStore({
        database: firebase.database(),
        reapInterval: 259200000
      }),
      secret: 'superS3cretPass',
      resave: true,
      saveUninitialized: true
    })
  );

  if (isDev) {
    server.use(morgan('dev'));
  }
};

```

**Comment by johnkorzhuk** [comment]
I think found my mistake: 

```javascript
  server.use(
    session({
      store: new FirebaseStore({
        database: firebase.database(),
        reapInterval: 259200000
      }),
      secret: 'superS3cretPass',
      resave: true,
      saveUninitialized: true,
      cookie: { maxAge: 259200000 }
    })
  );
```

Should store.reapInterval be equal to cookie.maxAge?

**Comment by benweier** [comment]
Hi @johnkorzhuk, you have indeed found the solution. The `cookie.maxAge` value is how long the cookie lasts _in the user's browser_ while the `reapInterval` value is the time between removal of expired sessions _in the Firebase store_. The distinction is important because reaping will only clean up expired sessions and can occur many times without impacting current sessions. Using a large interval means the Firebase store will continue to hold onto expired session data long after the user session has been invalidated.

It's worth noting that the `reapInterval` and the `cookie.maxAge` don't need to be the same value. In your example the expired session reaping would occur once every 3 days which may result in a large number of expired sessions hanging around in Firebase.

**Comment by johnkorzhuk** [comment]
@benweier Thanks for the quick response. On a weekend too! 👊  

I do have another question. How scaleable is using firebase to store sessions? Is there any point where it might be a good idea to introduce another form of session storage. It does feel a little strange to use a real-time database to store sessions.

**Comment by benweier** [comment]
Firebase itself is highly performant. [This post](https://groups.google.com/forum/#!topic/firebase-angular/OY7xtpoc9XA) should give you an idea of how well it scales with your demands.

As for when you should consider another form of storage, it all depends on your unique use-cases. A session store may not be the original intention for a real-time database but it is still suitable for the task up to a point so there's no reason why you shouldn't leverage the same data layer if it meets your needs.

I personally consider using a different session store to my data store in cases where sessions and data are non-dependent, or the data requirements mean that sessions can't feasibly sit with my app data. It all comes down to if you need to separate your storage concerns: highly-available persistent data - like sessions/core data - stored in Firebase; fast, ephemeral data - like caches - stored in Redis; long-term, infrequent data gets migrated to Mongo.

**Comment by johnkorzhuk** [comment]
Thank you, I appreciate your help.
