### ISSUE TITLE
firestore is possible?

### ISSUE THREAD

**Issue by alexandregiordanelli** [benweier/connect-session-firebase#70]

**Comment by benweier** [comment]
Hi @alexandregiordanelli, I skimmed the Firestore docs a few days ago and my initial reaction was that `connect-session-firebase` _could_ work with either no changes or very little. I'll write up a few test cases to confirm my thoughts and update documentation

**Comment by ashline** [comment]
Any progress on this?

**Comment by benweier** [comment]
Due to the API differences between Realtime Database and Cloud Firestore, this library won't work with a Firestore reference. I can publish a new library designed to work with Firestore if this is desired

**Comment by benweier** [comment]
[connect-session-firestore](https://www.npmjs.com/package/connect-session-firestore) is now available on npm. If you have any problems please open an issue on [its repository](https://github.com/benweier/connect-session-firestore)
