### ISSUE TITLE
"Session not in store" error is unhandled - Do I need to handle this in client code?

### ISSUE THREAD

**Issue by JustCallMeDanTheMan** [benweier/connect-session-firebase#95]
I am using connect-session-firebase with express and express-session. I have a few basic pages, but some require a login to access them.

Occasionally, when visiting one of these pages, I receive:
```
Error: Session 'SOME_LONG_ID_REMOVED' does not exist at session.once.then.snapshot (/user_code/node_modules/connect-session-firebase/lib/connect-session-firebase.js:99:21) at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

I first encountered it when switching from storage (testing) to connect-session-firebase (which I will use in production), and it was obvious to me that the session ID stored in my browser cookies cannot be found in the firebase store since they were never saved there in the first place. I manually cleared cookies in the browser and solved my problem.

Sometimes (rarely), however, I still get the above error. Perhaps a session expired on server-side and was removed from the firebase database before the browser removed it, so I visited and the session ID from my cookie is not found....? Not sure to be honest.

No worries, I would be happy to reset the session cookie for the user when they visit the page and this error occurs, but the current advice for set up does not mention how to handle this error, and my googling is revealing nothing.

I am using latest version 5.12.0 with express-session v 1.15.6 and firebase v 5.12.1

My set up step is:
```javascript
expressApp.use(expressAppSession({
	store: new firebaseExpressAppSession({
		database: firebaseApp.database()
	}),
	secret: 'THIS IS NOT MY REAL SECRET',
	resave: true,
	saveUninitialized: false // Example had true, but needs to be false due to GDPR restrictions
	//cookie: { secure: true } // Broke implementation. Not strictly necessary, so removed
}));
```

I notice this error was added from a recent update:
```javascript
return fn(new Error(`Session '${key}' does not exist`))
```

So, how should I handle this eventuality in client code? Right now it crashes my function out completely and leaves me on an `Internal Server Error` page.

If there is a standard way of handling such a scenario that I have been unable to find, can it be linked to from and/or added to the README.md?

**Comment by benweier** [comment]
Hi DanTheMan, you shouldn't need to handle this in client code. The session middleware would take care of it for you. This is a bit odd because trying to get a reaped session is handled the same way as other similar libraries. I'll take a look to see what I can improve

**Comment by JustCallMeDanTheMan** [comment]
Thanks,

Yes, I noticed e.g. express-session-mongo does the same thing in its `get` function, calling:
```javascript
            if (err) {
                fn && fn(err);
            }
```

thereby throwing the error out into the next middleware component.

So, I wrote an error handler to use as middleware, after all other `use` declarations have been made. When I caught the error there, I first tried to call `request.session.regenerate()` but, naturally, `request.session` was `undefined`.

So, harder googling reveals others having to wonder how to deal with undefined `request.session`, which is the main symptom of a failed session setup, and some tried to advise going back through the middleware... (https://github.com/expressjs/session/issues/99) but I know in THIS situation that would be unhelpful as it isn't a transient database error, it is a bad Session ID, and the error would recur ad infinitum.

So, instead, I coded an error handler to remove the cookie and redirect to a 'safe' page. In fact, it redirects to the same original URL, which will generate a new and valid session ID, but if logins were involved I would probably add some code to ensure users are logged out and redirected to e.g. `/loggedOut` or similar.

Here is what I added, after all other `use` statements:

```javascript
// Catch session ID errors (they seem to happen relatively infrequently)
expressApp.use((error, request, response, next) => {
	var errorObject;
	if (error) {
		errorObject = (typeof error === "object" && error.toJSON) ? error.toJSON() : { message: error.toString() };
	}

	var firebaseExpressAppSessionError = "Session '" + request.sessionID + "' does not exist"; // This is the precise error that connect-session-firebase will throw
	if (errorObject && errorObject.message && errorObject.message === firebaseExpressAppSessionError) {
		debugLogForAdmin("error", "App encountered a session error, attempting to clear the cookie", error);
		if (request.originalUrl) {
			response.clearCookie('connect.sid', { path: '/', maxAge: null, httpOnly: true, secure: false }).redirect(request.originalUrl);
		} else {
			debugLogForAdmin("error", "App could not find original destination to redirect to after session reset", error);
			response.clearCookie('connect.sid', { path: '/', maxAge: null, httpOnly: true, secure: false }).status(500).send(simpleHTMLErrorMessage("Server Error","Sorry, something went wrong while trying to process your request. Please try again."));
		}

	} else {
		next(error);
	}
});

// Catch all other errors and present a generic response to the user
expressApp.use((error, request, response, next) => {
	debugLogForAdmin("error", "App generated an error", error);
	response.status(500).send(simpleHTMLErrorMessage("Server Error","Sorry, something went wrong while trying to process your request. Please try again."));
});
```

Where the call to `clearCookie()` assumes the default cookie options are used in express-session setup (e.g. `session({...})` has no, or matching, cookie options in the options object passed)

The unfamiliar code here (`error.toJSON()`,`debugLogForAdmin()` and `simpleHTMLErrorMessage()`) are functions from my implementation that do simple things:

`error.toJSON()` safely generates an object from which the message etc. can be referenced, as I had otherwise found difficulty in querying the full error object inc. line number etc. - see https://github.com/AVVS/error-tojson

`debugLogForAdmin()` dumps log entries and, optionally, `error` objects that might include personally identifiable information into a secure location, and outside semi-permanent server logs.

`simpleHTMLErrorMessage()` generates a nice looking web page for a given error and message, matching our brand.



I'll keep testing and report back whether I see these error entries in my logs and only get barely-noticeable redirects for the user, as is intended. So far, so good.

**Comment by benweier** [comment]
Thanks for the detailed breakdown, DanTheMan. I've looked at a few more session libraries and noticed some don't call the function with an error at all, they just silently move on. I'd be interested to know whether their users have a similar issue. I may opt to remove the error completely since it doesn't appear to be handled by the session middleware and it's a bit awkward to expect everyone to do it themselves.

**Comment by JustCallMeDanTheMan** [comment]
No worries!

I can confirm the approach above worked for me. I was playing around with various login flows and redirect pages etc. and afterwards checked my logs for some other purpose. I saw my error logging had triggered:

```javascript
debugLogForAdmin("error", "App encountered a session error, attempting to clear the cookie", error);
```

Though, as a 'user', I didn't notice anything adverse at all. The second error was not recorded in my logs, so I know the redirect to `request.originalUrl` was triggered. My session must have been repaired by the deletion of the old cookie and the re-application of a new cookie with a valid session ID, and the redirect must have happened without me even noticing. For me, that's perfect.

I have downgraded that from an `error` to simple `log` in my code, and will proceed to forget all about it.


Rather than remove the error from connect-session-firebase, if you do want to change that behaviour, perhaps you could make it an option for your constructor? Something like `throwErrorOnSessionIDNotFound` that could be set to `true` or `false` or omitted for whatever default you feel is best. That way, I can choose to avoid silently broken sessions that I don't know about and can't handle, as I imagine it might cause hard-to-diagnose problems with maintaining an authenticated state for the end user, if they have a cookie with an invalid session ID that doesn't get reset until it expires (I am also using passport).

I know I certainly prefer loud errors that tell me I need to add code to handle an eventuality I might not othrerwise have considered :)

**Comment by benweier** [comment]
That's a good suggestion. I think a custom error object behind `errorIfSessionNotFound: false` (by default) would work for users who care about it, and want to handle this use-case themselves.

I've gone digging through [express-session](https://github.com/expressjs/session/blob/104725ebcb1c8ef9a242ea18577d1f34885974a0/index.js#L461-L474) for a clearer understanding of the way it handles errors. The session middleware looks like it doesn't consider a missing session to be an "error", instead it assumes any `err` to be an actual problem with whatever is attempting to fetch a session (e.g. a network proxy/database connection/file system permission error).

I'll release an update over the weekend to address this. Thanks again! :)

**Comment by JustCallMeDanTheMan** [comment]
I have updated to `5.13.0 `and set `errorIfSessionNotFound` to `true` in options:

```javascript
expressApp.use(expressAppSession({
	store: new firebaseExpressAppSession({
		database: firebaseApp.database(),
		errorIfSessionNotFound: true
	}),
	secret: 'THIS IS NOT MY REAL SECRET',
	resave: true,
	saveUninitialized: false // Example had true, but needs to be false due to GDPR restrictions
	//cookie: { secure: true } // Broke implementation. Not strictly necessary, so removed
}));
```

Works perfectly. Thanks!
