### ISSUE TITLE
How to destroy sessions in store?

### ISSUE THREAD

**Issue by ramonsgds** [benweier/connect-session-firebase#96]
Everything has been working fine so far.

After a user reaches the maxAge limit or closes the browser  (such that he does not logout through a logout button in which I call `session.destroy` explicit) the sessions continue to exist and are not destroyed in the Firebase Database.

What should I do?

**Comment by benweier** [comment]
Sessions in the database are not immediately deleted when they reach their max age. To handle this there is a `reap` method that cleans up all expired sessions on a schedule (default 6hrs). You can modify this reap schedule by passing a `reapInterval` value (in milliseconds) alongside your database instance


```
express()
  .use(session({
    store: new FirebaseStore({
      database: ref.database(),
      reapInterval: 600000, // 10min
    }),
  }))
```

You can also "do something" (such as logging into messages) whenever a reap occurs by passing a `reapCallback` function as well. This function accepts no arguments about which sessions or how many were reaped, so if you'd like that info I can look at adding it.

```
express()
  .use(session({
    store: new FirebaseStore({
      database: ref.database(),
      reapInterval: 600000, // 10min
      reapCallback: () => {
        console.log('sessions reaped')
      },
    }),
  }))
```
